version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: backend
    ports:
      - 5432:5432

  # backend:
  #   build: .
  #   ports:
  #     - "3000:3000" # Ajuste a porta conforme necessário
  #   depends_on:
  #     - postgres

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080